export const SAVE_DATA_FAILD="SAVE_DATA_FAILD";
export const CLEAR_INPU_FIELD='CLEAR_INPU_FIELD';
export const CLEAR_SUCCESS_MESSAGE='CLEAR_SUCCESS_MESSAGE';

export const ACCESS_DATA_SUCCESS='ACCESS_DATA_SUCCESS';

export const EDIT_INPUTS_DATA_ASIGN='EDIT_INPUTS_DATA_ASIGN';
export const SAVE_DATA_SUCCESS='SAVE_DATA_SUCCESS';

export const COUNT_DOCUMENT='COUNT_DOCUMENT';

export const UPDATE_DATA_STATE='UPDATE_DATA_STATE';

export const CLEAR_DATA_STATE='CLEAR_DATA_STATE';

export const FIND_DATA='FIND_DATA';
export const DELETE_LOCAL_SEARCH='DELETE_LOCAL_SEARCH';